### ISSUE TITLE
Can't import an aws:iam:UserLoginProfile

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-aws#686]
I converted this TF snippet

```hcl
resource "aws_iam_user_login_profile" "ringo" {
  user    = aws_iam_user.ringo.name
  pgp_key = "keybase:ringods"
}
```

to Pulumi TS code

```typescript
const iam_user_login_profile_ringo = new aws.iam.UserLoginProfile("ringo",
    {
        user: iam_user_ringo.name,
        pgpKey: "keybase:ringods"
    },
    {
        import: "ringo"
    })
```
But on preview, I get this warning:

```shell
...
=   └─ aws:iam:UserLoginProfile  ringo                       import     [diff: +pgpKey]; 1 warning

Diagnostics:
  aws:iam:UserLoginProfile (ringo):
    warning: inputs to import do not match the existing resource; importing this resource will fail
```

The PGP key indicator is the same string. How come a difference is detected?

To get around this, I removed my AWS Console login password and instead of importing the resource, I let Pulumi create a new resource.

Context: https://pulumi-community.slack.com/archives/C84L4E3N1/p1563531696021800

**Comment by stack72** [comment]
ok, so i've spent a wee bit of time looking into this because I know this part of the AWS codebase. Basically, what happens is as follows:

1. Create passes a required username and pgpKey to the provider and sets the fingerprint and also the enrypted_password to state in the Create func.
2. Read sets the User only to state
3. NOTHING sets the PGP Key to state

So Pulumi import is failing because the API requires username and pgpkey, but only user is actually being set in the Read func.

Right now, there is 0 ways of making this resource importable due to the fact that Create does all of the work...

I guess we need to think about this internally and see what we can do

Paul

**Comment by ringods** [comment]
@stack72 it is indeed a tricky one. Usually, the creation of the resources provides you a single time with the generated user credentials. After that, it can't be retrieved from AWS again. I have also been thinking about this.

What might be an option is that importing this resource would warn the user that a new set of credentials would be generated and returned. I could live with such a scenario as it prevents me of my workaround of going to the AWS console to remove credentials and then letting them be created.

**Comment by lukehoban** [comment]
@pgavlin will `ignoreChanges` work here to allow the import to succeed and prevent replacements after import?

**Comment by pgavlin** [comment]
Yes, it should. I was attempting to test this today, but have not yet been able to as keybase appeared to be unreachable earlier this morning.

**Comment by pgavlin** [comment]
I have confirmed that the new `ignoreChanges` support fixes this issue.

**Comment by pgavlin** [comment]
This is fixed as of v0.18.27. The import should succeed if you use `ignoreChanges` to ignore the delta in the `pgpKey` field:

```
const iam_user_login_profile_ringo = new aws.iam.UserLoginProfile("ringo",
    {
        user: iam_user_ringo.name,
        pgpKey: "keybase:ringods"
    },
    {
        import: "ringo"
        ignoreChanges: [ "pgpKey" ],
    })
```

**Comment by n2taylor** [comment]
This doesn't work for me. I'm doing it exactly as in the example. 

If I add `pgpKey` to `ignoreChanges` but keep it in the `UserLoginProfileArgs`, I get `Required attribute is not set`

If I remove `pgpKey` from `ignoreChanges` but keep it in the `UserLoginProfileArgs`, I get `inputs to import do not match the existing resource`, since `pgpKey` does not exist on it.

**Comment by alvis** [comment]
@pgavlin I can confirm that the issue remains as of 3.18.1.

When using
```ts
{
    import: "<username>"
    ignoreChanges: [ "pgpKey" ],
}
```

it shows
`error: aws:iam/userLoginProfile:UserLoginProfile resource '<resource name>' has a problem: Missing required argument: The argument "pgp_key" is required, but no definition was found.. Examine values at 'UserLoginProfile.PgpKey'.`

Interesting enough, if I use `PgpKey` instead of `pgpKey` as suggested, I can bypass this error, but still result in another error: `error: inputs to import do not match the existing resource`
