### ISSUE TITLE
Lambda environment change isn't picked up

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-aws#751]
Run `pulumi up` on the following program:

``` ts
import * as aws from "@pulumi/aws";
import * as pulumi from "@pulumi/pulumi";

const role = new aws.iam.Role("mylambda-role", {
    assumeRolePolicy: aws.iam.assumeRolePolicyForPrincipal({ Service: "lambda.amazonaws.com" }),
});

const lambda = new aws.lambda.Function("mylambda", {
    runtime: aws.lambda.DotnetCore2d1Runtime,
    code: new pulumi.asset.AssetArchive({
        ".": new pulumi.asset.FileArchive("./app/bin/Debug/netcoreapp2.1/publish"),
    }),
    timeout: 300,
    handler: "app::app.Functions::GetAsync",
    role: role.arn,
    environment: {
        variables: {
            FOO: "bar",
        },
    },
});
```
after the deployment succeeds, change `environment` to
``` ts
    environment: {
        variables: {
            BUZZ: "fizz",
        },
    },
```

Expected: `pulumi up` overrides `environment`.
Current result: `preview` has no changes and `up` deploys nothing.

Note: the env variable name has to be in UPPERCASE (may also contain `_`). Lowercase changes are detected.

**Comment by pgavlin** [comment]
@mikhailshilkov any chance you can share the contents of `./app/bin/Debug/netcoreapp2.1/publish` ?

**Comment by pgavlin** [comment]
And do you have the equivalent TF config?

**Comment by danfhernandez** [comment]
I also have an example here if this is helpful: 

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const role = new aws.iam.Role("webhook-router-lambda-role", {
    assumeRolePolicy: JSON.stringify({
        Version: "2012-10-17",
        Statement: [{
            Action: "sts:AssumeRole",
            Principal: {
                Service: "lambda.amazonaws.com"
            },
            Effect: "Allow",
            Sid: "",
        }]
    })
});

new aws.iam.RolePolicyAttachment('webhook-router-lambda-basic-execution-policy', {
    role: role,
    policyArn: aws.iam.ManagedPolicies.AWSLambdaBasicExecutionRole
});

const routeTable = new aws.dynamodb.Table("route", {
    attributes: [
        {name: "Id", type: "S"},
    ],
    hashKey: "Id",
    billingMode: 'PROVISIONED',
    readCapacity: 1,
    writeCapacity: 1,
});

const webhookRouterLambda = new aws.lambda.Function("webhook-router", {
    runtime: aws.lambda.Go1dxRuntime,
    code: new pulumi.asset.FileArchive("./build/helloworld.zip"),
    timeout: 1,
    handler: "main",
    role: role.arn,
    publish: true,
    environment: {
        variables: {
            DYNAMODB_ROUTE_TABLE_NAME: routeTable.name
        }
    }
});
```

[helloworld.zip](https://github.com/pulumi/pulumi-aws/files/3637038/helloworld.zip)

**Comment by mikhailshilkov** [comment]
@pgavlin You can build it from https://github.com/pulumi/examples/tree/master/aws-ts-serverless-raw but you don't really need it, just zip any folder really, you don't need lambda to work to reproduce. Or you the one from @danfhernandez 

TF:

```hcl
provider "aws" {
  version = "~> 2.0"
}

resource "aws_iam_role" "iam_for_lambda" {
  name = "iam_for_lambda"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_lambda_function" "test_lambda" {
  filename      = "helloworld.zip"
  function_name = "lambda_function_name"
  role          = "${aws_iam_role.iam_for_lambda.arn}"
  handler       = "exports.test"

  source_code_hash = "${filebase64sha256("helloworld.zip")}"

  runtime = "nodejs8.10"

  environment {
    variables = {
      FOO = "bar"
    }
  }
}
```

**Comment by barakbaronk** [comment]
@pgavlin was this issue resolved in python pulumi-aws libraries?
I'm seeing the same issue using pulumi-aws 3.33.0 and pulumi 2.23.1

**Comment by giladgurvich** [comment]
@pgavlin we still have this issue :( 
Pulumi doesn't update env vars. We see it in the diff but it does not reflect the changes in AWS.
We are using pulumi-aws 4.15.0 (Python)

**Comment by slikk66** [comment]
Seems like it's still an issue, just added a new env var, and it's not being recognized:

````
root@7b912ce82f67:/data/pulumi# pulumi version
v3.143.0

root@7b912ce82f67:/data/pulumi# pulumi plugin ls
NAME    KIND      VERSION  SIZE    INSTALLED    LAST USED
aws     resource  6.6.0    582 MB  3 days ago   5 hours ago
docker  resource  3.6.1    40 MB   3 weeks ago  3 weeks ago
````
